version: '3.9'

networks:
  shared_network:
    driver: bridge

services:
  kitchen:
    container_name: kitchen
    build:
      context: .
      dockerfile: kitchen-Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared_network
    volumes:
      - "./containers_data:/home/containers_data"

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - shared_network
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Service used to inspect database. Use "db" for hostname.
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - shared_network
    ports:
      - 8080:8080
